"use client";
import {useMemo,useState} from "react";

type Telemetry={altitude:number;speed:number;heading:number;battery:number;gps:string;armed:boolean};
const initial:Telemetry={altitude:10.0,speed:5.0,heading:92,battery:87,gps:"16.9831, 74.1570",armed:false};
export default function Page(){
 const [t,setT]=useState(initial); const [decision,setDecision]=useState("READY"); const [mission,setMission]=useState("HOLD"); const [events,setEvents]=useState<string[]>([]);
 const status=useMemo(()=>decision==="ALLOW"?"AUTHORIZED":decision==="BLOCK"?"BLOCKED":"STANDBY",[decision]);
 function govern(next:string){setMission(next);setDecision(next==="LAND"?"REVIEW":"ALLOW"); if(next==="TAKEOFF")setT(v=>({...v,armed:true,altitude:12})); if(next==="LAND")setT(v=>({...v,armed:false,altitude:0,speed:0})); if(next==="MOVE")setT(v=>({...v,heading:(v.heading+12)%360,speed:8}));}
 return <main className="shell"><header><div><div className="eyebrow">SCIИENTIA × ASTRA</div><h1>Drone Simulator</h1><p>Governed simulation control plane</p></div><div className={"status "+status.toLowerCase()}><span/> {status}</div></header>
 <section className="grid hero"><div className="card viewport"><div className="cardhead"><span>SIMULATION WORLD</span><span>PX4 SITL · GAZEBO</span></div><div className="sky"><div className="gridline"/><div className="drone"><div className="rotor r1"/><div className="rotor r2"/><div className="rotor r3"/><div className="rotor r4"/><div className="body"/></div><div className="hud">ALT {t.altitude.toFixed(1)} m<br/>SPD {t.speed.toFixed(1)} m/s</div></div><div className="worldbar"><span>● WORLD MODEL SYNCED</span><span>Wind 4.2 m/s NW</span></div></div>
 <div className="card telemetry"><div className="cardhead"><span>TELEMETRY</span><span className="live">LIVE</span></div><div className="metrics">{[["ALTITUDE",t.altitude.toFixed(1)+" m"],["SPEED",t.speed.toFixed(1)+" m/s"],["HEADING",t.heading+"°"],["BATTERY",t.battery+"%"],["GPS",t.gps],["FLIGHT STATE",t.armed?"ARMED":"DISARMED"]].map(([a,b])=><div className="metric" key={a}><small>{a}</small><strong>{b}</strong></div>)}</div><div className="battery"><span style={{width:t.battery+"%"}}/></div></div></section>
 <section className="grid lower"><div className="card mission"><div className="cardhead"><span>MISSION CONTROL</span><span>ASTRA POLICY: SIMULATION</span></div><div className="proposal"><div><small>PROPOSAL</small><strong>{mission}</strong></div><div className="arrow">→</div><div><small>AUTHORIZATION</small><strong>{decision}</strong></div><div className="arrow">→</div><div><small>EXECUTION</small><strong>{decision==="ALLOW"?"READY":"HELD"}</strong></div></div><div className="controls">{["TAKEOFF","MOVE","HOLD","LAND"].map(x=><button key={x} onClick={()=>govern(x)} className={x===mission?"active":""}>{x}</button>)}</div></div>
 <div className="card evidence"><div className="cardhead"><span>EVIDENCE</span><span>TRACE</span></div><div className="event"><b>ASTRA_EXECUTION_DECISION</b><span>{decision}</span></div><div className="event"><b>effect_policy</b><span>{decision==="ALLOW"?"MUTATION_PERMITTED":"NO_STATE_CHANGE"}</span></div>{events.map((e,i)=><div className="event" key={i}><b>event_{i+1}</b><span>{e}</span></div>)}<div className="event"><b>resource</b><span>drone://simulator</span></div><div className="event"><b>capability</b><span>drone.flight</span></div><div className="event"><b>scope</b><span>zone=simulation</span></div><div className="event"><b>pipeline</b><span>SCIИENTIA → ASTRA → PX4</span></div></div></section>
 <footer><span>CAPABILITY ≠ PERMISSION</span><span>Authorization precedes execution · Simulation only · Evidence retained</span></footer></main>}
