"use client";
import { useMemo, useState } from "react";
type Decision = "ALLOW" | "DENY" | "APPROVAL_REQUIRED";
type Agent = { id:string; name:string; risk:string; status:string; actions:number };
type Event = { id:string; time:string; agent:string; tool:string; decision:Decision; reason:string };
const initialAgents:Agent[]=[
{id:"agent-soc",name:"SOC Analyst",risk:"medium",status:"active",actions:2841},
{id:"agent-deploy",name:"Production Deployer",risk:"high",status:"active",actions:913},
{id:"agent-research",name:"Research Agent",risk:"low",status:"active",actions:4672}];
const initialEvents:Event[]=[
{id:"evt-1042",time:"10:42:18",agent:"SOC Analyst",tool:"create_ticket",decision:"ALLOW",reason:"policy:security-ticket-v3"},
{id:"evt-1041",time:"10:41:52",agent:"Research Agent",tool:"external_api",decision:"DENY",reason:"scope not permitted"},
{id:"evt-1040",time:"10:40:31",agent:"Production Deployer",tool:"deploy",decision:"APPROVAL_REQUIRED",reason:"production write requires approval"}];
const tools=["create_ticket","external_api","read_database","deploy","delete_resource"];
export default function Page(){
const[agents,setAgents]=useState(initialAgents),[events,setEvents]=useState(initialEvents),[selectedAgent,setSelectedAgent]=useState(initialAgents[1].id),[selectedTool,setSelectedTool]=useState("delete_resource"),[resource,setResource]=useState("production/database"),[decision,setDecision]=useState<Decision>("DENY"),[reason,setReason]=useState("scope not permitted"),[pending,setPending]=useState(false),[notice,setNotice]=useState("");
const selected=useMemo(()=>agents.find(a=>a.id===selectedAgent)!,[agents,selectedAgent]);
async function authorize(){setPending(true);setNotice("");try{const response=await fetch("/api/v1/authorize",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({agent_id:selectedAgent,tool:selectedTool,action:selectedTool==="delete_resource"?"delete":"execute",resource,context:{environment:resource.startsWith("production")?"production":"simulation"}})});const data=await response.json();setDecision(data.decision);setReason(data.reason);setEvents(current=>[{id:data.authorization_id,time:new Date().toLocaleTimeString([], {hour12:false}),agent:selected.name,tool:selectedTool,decision:data.decision,reason:data.reason},...current].slice(0,12));setAgents(current=>current.map(a=>a.id===selected.id?{...a,actions:a.actions+1}:a));setNotice(data.decision==="ALLOW"?"Authorization granted.":data.decision==="APPROVAL_REQUIRED"?"Human approval required before execution.":"Execution blocked by policy.");}catch{setNotice("Authorization service unavailable.");setDecision("DENY");setReason("governance service unavailable");}finally{setPending(false)}}
function revoke(){setAgents(current=>current.map(a=>a.id===selected.id?{...a,status:"revoked"}:a));setNotice(selected.name+" authority revoked.");setDecision("DENY");setReason("agent authority revoked");}
return <main className="shell"><header className="topbar"><div><div className="eyebrow">SCIИENTIA × ASTRA</div><h1>Agent Governance Control Plane</h1><p>Authorize, observe, evidence, and revoke AI-agent actions.</p></div><div className="header-actions"><span className="env-badge"><i/> PROTOTYPE · FAIL-CLOSED</span><button className="revoke" onClick={revoke}>REVOKE SELECTED</button></div></header>
<section className="stats"><div><small>ACTIVE AGENTS</small><strong>{agents.filter(a=>a.status==="active").length}</strong></div><div><small>GOVERNED ACTIONS</small><strong>{agents.reduce((n,a)=>n+a.actions,0).toLocaleString()}</strong></div><div><small>BLOCKED / HELD</small><strong>{events.filter(e=>e.decision!=="ALLOW").length}</strong></div><div><small>AUTHORITY</small><strong className="accent">ENFORCED</strong></div></section>
<section className="layout"><div className="stack"><div className="card"><div className="cardhead"><span>AUTHORIZATION CONSOLE</span><span>POST /api/v1/authorize</span></div><div className="form-grid"><label>AGENT<select value={selectedAgent} onChange={e=>setSelectedAgent(e.target.value)}>{agents.map(a=><option key={a.id} value={a.id}>{a.name} · {a.status}</option>)}</select></label><label>TOOL<select value={selectedTool} onChange={e=>setSelectedTool(e.target.value)}>{tools.map(t=><option key={t}>{t}</option>)}</select></label><label className="wide">RESOURCE<input value={resource} onChange={e=>setResource(e.target.value)}/></label></div><div className={"decision "+decision.toLowerCase()}><div><small>ASTRA DECISION</small><strong>{decision}</strong></div><div className="decision-reason">{reason}</div></div><div className="action-row"><button className="primary" onClick={authorize} disabled={pending||selected.status!=="active"}>{pending?"EVALUATING…":"EVALUATE AUTHORIZATION"}</button><span className="hint">Capability ≠ Permission</span></div>{notice&&<div className="notice">{notice}</div>}</div>
<div className="card"><div className="cardhead"><span>AUTHORIZATION PIPELINE</span><span>FAIL-CLOSED</span></div><div className="pipeline">{["IDENTITY","POLICY","RISK","DECISION","ACTION","EVIDENCE"].map((x,i)=><div key={x} className="node"><b>{String(i+1).padStart(2,"0")}</b><span>{x}</span></div>)}</div></div>
<div className="card"><div className="cardhead"><span>AGENT REGISTRY</span><span>{agents.length} REGISTERED</span></div><div className="table"><div className="row header"><span>AGENT</span><span>RISK</span><span>STATUS</span><span>ACTIONS</span></div>{agents.map(a=><button key={a.id} className={"row "+(a.id===selectedAgent?"selected":"")} onClick={()=>setSelectedAgent(a.id)}><span>{a.name}<small>{a.id}</small></span><span>{a.risk}</span><span className={a.status}>{a.status}</span><span>{a.actions.toLocaleString()}</span></button>)}</div></div></div>
<aside className="stack"><div className="card"><div className="cardhead"><span>LIVE GOVERNANCE</span><span className="live">● LIVE</span></div><div className="governance-hero"><div className={"big-decision "+decision.toLowerCase()}>{decision}</div><p>{selected.name}</p><small>{selectedTool} → {resource}</small></div></div>
<div className="card evidence"><div className="cardhead"><span>EVIDENCE TRACE</span><span>APPEND-ONLY</span></div>{events.map(e=><div className="event" key={e.id}><div><b>{e.agent}</b><small>{e.time} · {e.tool}</small></div><span className={e.decision.toLowerCase()}>{e.decision}</span><small>{e.reason}</small></div>)}</div>
<div className="card invariant"><div className="cardhead"><span>GOVERNANCE INVARIANT</span></div><strong>DENY → NO AUTHORIZATION → NO EXECUTION → EVIDENCE</strong><p>ASTRA separates an agent’s technical capability from the authority required to exercise it.</p></div></aside></section>
<footer><span>ASTRA GOVERNOR · PRODUCTION PROTOTYPE</span><span>Authorization precedes execution · Evidence follows every decision</span></footer></main>}
